### ISSUE TITLE
PredicateBuilder is not compatible dotnet 6

### ISSUE THREAD

**Issue by artizani** [armanab/CleanArchitecture#2]
PredicateBuilder is not compatible dotnet 6 in 

src/Common/Application/Users/Queries/GetUsersAdmin/GetUsersQuery.cs

**Comment by armanab** [comment]
> PredicateBuilder is not compatible dotnet 6 in
> 
> src/Common/Application/Users/Queries/GetUsersAdmin/GetUsersQuery.cs

I will upgrade to .NET 6 as soon as possible

**Comment by armanab** [comment]
> PredicateBuilder is not compatible dotnet 6 in
> 
> src/Common/Application/Users/Queries/GetUsersAdmin/GetUsersQuery.cs

Hello, I upgraded the project to .NET 6.
And I also tested GetUsersQuery, there was no problem. I added a UserController to test this command and CRUD users.

I pushed the code and you just need to pull it from master branch
